# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
revisionHistoryLimit: 1
image:
  tag: latest
  pullPolicy: Always
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
service:
  name: go
  type: ClusterIP
  servicePort: 80